<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="atoum testsuite">
  <testsuite name="SubscribersList" package="Vendor\Calendar\test\units" tests="7" failures="0" errors="0" skipped="0" time="0.054648160934448">
    <testcase name="testNoSubChoice" time="0.0015850067138672" classname="Vendor\Calendar\test\units\SubscribersList" assertions="0"/>
    <testcase name="testAddMultipleSubs" time="0.0082888603210449" classname="Vendor\Calendar\test\units\SubscribersList" assertions="1"/>
    <testcase name="testMultiplePersonChoice" time="0.017397165298462" classname="Vendor\Calendar\test\units\SubscribersList" assertions="2"/>
    <testcase name="testEmptyInit" time="0.0074479579925537" classname="Vendor\Calendar\test\units\SubscribersList" assertions="4"/>
    <testcase name="testPopulatedChoice" time="0.0053861141204834" classname="Vendor\Calendar\test\units\SubscribersList" assertions="3"/>
    <testcase name="testAddSubscribers" time="0.0065000057220459" classname="Vendor\Calendar\test\units\SubscribersList" assertions="2"/>
    <testcase name="testWithUndisponiblePersons" time="0.0080430507659912" classname="Vendor\Calendar\test\units\SubscribersList" assertions="2"/>
  </testsuite>
  <testsuite name="Auth" package="Vendor\Gestion\test\units" tests="6" failures="0" errors="3" skipped="0" time="0.0053939819335938">
    <testcase name="testCreateSession" time="0.0022168159484863" classname="Vendor\Gestion\test\units\Auth" assertions="0"/>
    <testcase name="testIsLogged" time="0.0016200542449951" classname="Vendor\Gestion\test\units\Auth" assertions="4"/>
    <testcase name="testLogout" time="0.0015571117401123" classname="Vendor\Gestion\test\units\Auth" assertions="1"/>
    <testcase name="testConnectionOK" time="0" classname="Vendor\Gestion\test\units\Auth" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/Gestion/Auth.php(17): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/Gestion/TestAuth.php(34): Vendor\Gestion\Auth->__construct()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\Gestion\test\units\Auth->testConnectionOK()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testConnectionO...')
#6 {main}]]></error>
    </testcase>
    <testcase name="testConectionKO" time="0" classname="Vendor\Gestion\test\units\Auth" assertions="1">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/Gestion/Auth.php(17): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/Gestion/TestAuth.php(41): Vendor\Gestion\Auth->__construct()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\Gestion\test\units\Auth->testConectionKO()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testConectionKO')
#6 {main}]]></error>
    </testcase>
    <testcase name="testConnectionInjection" time="0" classname="Vendor\Gestion\test\units\Auth" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/Gestion/Auth.php(17): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/Gestion/TestAuth.php(48): Vendor\Gestion\Auth->__construct()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\Gestion\test\units\Auth->testConnectionInjection()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testConnectionI...')
#6 {main}]]></error>
    </testcase>
  </testsuite>
  <testsuite name="Registration" package="Vendor\Gestion\test\units" tests="2" failures="0" errors="1" skipped="0" time="1.215934753418E-5">
    <testcase name="testRegistration" time="1.215934753418E-5" classname="Vendor\Gestion\test\units\Registration" assertions="0"/>
    <testcase name="testUsernameNotUsed" time="0" classname="Vendor\Gestion\test\units\Registration" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/Gestion/Registration.php(17): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/Gestion/TestRegistration.php(19): Vendor\Gestion\Registration->__construct()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\Gestion\test\units\Registration->testUsernameNotUsed()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testUsernameNot...')
#6 {main}]]></error>
    </testcase>
  </testsuite>
  <testsuite name="Mail" package="Vendor\Mailing\tests\units" tests="4" failures="0" errors="0" skipped="0" time="0.008120059967041">
    <testcase name="testGetRecipients" time="0.0024070739746094" classname="Vendor\Mailing\tests\units\Mail" assertions="0"/>
    <testcase name="testConstruct" time="0.0029668807983398" classname="Vendor\Mailing\tests\units\Mail" assertions="2"/>
    <testcase name="testGetSetSubject" time="0.0014879703521729" classname="Vendor\Mailing\tests\units\Mail" assertions="6"/>
    <testcase name="testGetSetBody" time="0.0012581348419189" classname="Vendor\Mailing\tests\units\Mail" assertions="2"/>
  </testsuite>
  <testsuite name="MailSender" package="Vendor\Mailing\tests\units" tests="2" failures="0" errors="0" skipped="0" time="0.86184406280518">
    <testcase name="testBadSender" time="0.33630394935608" classname="Vendor\Mailing\tests\units\MailSender" assertions="0"/>
    <testcase name="testBadCredentials" time="0.5255401134491" classname="Vendor\Mailing\tests\units\MailSender" assertions="2"/>
  </testsuite>
  <testsuite name="DAO" package="Vendor\DAO\tests\units" tests="6" failures="0" errors="6" skipped="0" time="0">
    <testcase name="testRequestConnexion" time="0" classname="Vendor\DAO\tests\units\DAO" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(12): Vendor\DAO\DAO->__construct()
#3 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\DAO\tests\units\DAO->testRequestConnexion()
#4 Standard input code(1): mageekguy\atoum\test->runTestMethod('testRequestConn...')
#5 {main}]]></error>
    </testcase>
    <testcase name="testCreationTables" time="0" classname="Vendor\DAO\tests\units\DAO" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(131): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(33): Vendor\DAO\tests\units\DAO->initialiserBDDTest()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\DAO\tests\units\DAO->testCreationTables()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testCreationTab...')
#6 {main}]]></error>
    </testcase>
    <testcase name="testAddPersonne" time="0" classname="Vendor\DAO\tests\units\DAO" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(131): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(51): Vendor\DAO\tests\units\DAO->initialiserBDDTest()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\DAO\tests\units\DAO->testAddPersonne()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testAddPersonne')
#6 {main}]]></error>
    </testcase>
    <testcase name="testGetPersonne" time="0" classname="Vendor\DAO\tests\units\DAO" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(131): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(73): Vendor\DAO\tests\units\DAO->initialiserBDDTest()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\DAO\tests\units\DAO->testGetPersonne()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testGetPersonne')
#6 {main}]]></error>
    </testcase>
    <testcase name="testUserExistant" time="0" classname="Vendor\DAO\tests\units\DAO" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(131): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(87): Vendor\DAO\tests\units\DAO->initialiserBDDTest()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\DAO\tests\units\DAO->testUserExistant()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testUserExistan...')
#6 {main}]]></error>
    </testcase>
    <testcase name="testUpdatePersonne" time="0" classname="Vendor\DAO\tests\units\DAO" assertions="0">
      <error type="Exception"><![CDATA[PDOException: SQLSTATE[HY000] [2002] Connection timed out in /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php:37
Stack trace:
#0 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(37): PDO->__construct('mysql:host=172....', 'm2test2', 'm2test2')
#1 /home/baptiste/Documents/M2/TF/m2test2/src/main/Vendor/DAO/DAO.php(20): Vendor\DAO\DAO->requestConnexion()
#2 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(131): Vendor\DAO\DAO->__construct()
#3 /home/baptiste/Documents/M2/TF/m2test2/src/test/Vendor/DAO/TestDao.php(111): Vendor\DAO\tests\units\DAO->initialiserBDDTest()
#4 phar:///home/baptiste/Documents/M2/TF/m2test2/applis/atoum/atoum.phar/1/classes/test.php(1363): Vendor\DAO\tests\units\DAO->testUpdatePersonne()
#5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testUpdatePerso...')
#6 {main}]]></error>
    </testcase>
  </testsuite>
</testsuites>
